// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJljGf2Ly5AcjZQwg0DuraUqQCGDZTxm4',
    appId: '1:495044399130:android:d9988b9865c9c6a78401a3',
    messagingSenderId: '495044399130',
    projectId: 'transcription-4f0f1',
    storageBucket: 'transcription-4f0f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUHKE0Af8D2Acm68mAC89mgtMWg5qbTW0',
    appId: '1:495044399130:ios:a3eb0fa7f17f50068401a3',
    messagingSenderId: '495044399130',
    projectId: 'transcription-4f0f1',
    storageBucket: 'transcription-4f0f1.appspot.com',
    androidClientId: '495044399130-l2bmbhq8k7dcfk2n0o3n3ek5ulnaut3a.apps.googleusercontent.com',
    iosClientId: '495044399130-9mrhrgq11qi3ve39cnd8u6nte9kekg9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalApp',
  );

}